<?xml version="1.0" encoding="UTF-8"?>

<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

<xsl:template match="pmd">

	<h1>Summary</h1>

	<table width="100%" cellspacing="0">
	  <tr class="summary">
		<th>Files</th>
		<th>Total</th>
		<th>Priority 1</th>
		<th>Priority 2</th>
		<th>Priority 3</th>
		<th>Priority 4</th>
		<th>Priority 5</th>
	  </tr>
	  <tr class="summary">
		<td><xsl:value-of select="count(//file)"/></td>
		<td><xsl:value-of select="count(//violation)"/></td>
		<td class="p1"><xsl:value-of select="count(//violation[@priority = 1])"/></td>
		<td class="p2"><xsl:value-of select="count(//violation[@priority = 2])"/></td>
		<td class="p3"><xsl:value-of select="count(//violation[@priority = 3])"/></td>
		<td class="p4"><xsl:value-of select="count(//violation[@priority = 4])"/></td>
		<td class="p5"><xsl:value-of select="count(//violation[@priority = 5])"/></td>
	  </tr>
	</table>

	<br/>
	<hr/>

	<h1>Details</h1>
	
	<xsl:for-each select="file">
		<xsl:sort data-type="number" order="descending" select="count(violation)"/>
		<!-- TODO: Include mxml -->
		<xsl:variable name="klass" select="substring-before(violation[1]/@class,'.as')" disable-output-escaping="yes"/>
		<xsl:variable name="package" select="violation[1]/@package" disable-output-escaping="yes"/>
		<xsl:variable name="itemid" select="$klass" />
		
		<div class="result">
			<h2><xsl:value-of select="$klass"/></h2>
			<div class="package"><xsl:value-of select="$package"/>.<xsl:value-of select="$klass"/></div>
			<div class="violationcount"><xsl:value-of select="count(violation)"/></div>
			<span class="showhide">
				<a>
					<xsl:attribute name="id">in<xsl:value-of select="$itemid"/>_h</xsl:attribute>
					<xsl:attribute name="style"></xsl:attribute> 
					<xsl:attribute name="href">javascript:hideElement('in<xsl:value-of select="$itemid"/>')</xsl:attribute>
					&#x25BC;
				</a>
				<a>
					<xsl:attribute name="id">in<xsl:value-of select="$itemid"/>_s</xsl:attribute>
					<xsl:attribute name="style">display: none;</xsl:attribute>
					<xsl:attribute name="href">javascript:showElement('in<xsl:value-of select="$itemid"/>')</xsl:attribute>
					&#x25B6;
				</a>
			</span>
			<div class="inner">
				<xsl:attribute name="id">in<xsl:value-of select="$itemid"/>_b</xsl:attribute>
				<xsl:attribute name="style">
					
				</xsl:attribute> 
				<table cellspacing="0" width="100%" class="details">
					<tr>
						<th/>
						<th>Line</th>						
						<th class="desc">Description</th>
					</tr>
					<xsl:for-each select="violation">
					<tr>
						<td><xsl:attribute name="class">p<xsl:value-of select="@priority"/></xsl:attribute></td>
						<td class="linkline" >
							<a><xsl:attribute name="href">txmt://open?url=file://<xsl:value-of select="../@name"/>&amp;line=<xsl:value-of disable-output-escaping="yes" select="@beginline"/>&amp;column=<xsl:value-of disable-output-escaping="yes" select="@begincolumn"/></xsl:attribute>
							<xsl:value-of disable-output-escaping="yes" select="@beginline"/>
							</a>
						</td>
						<td width="100%"><xsl:value-of disable-output-escaping="yes" select="."/></td>
					</tr>
					</xsl:for-each>
				</table>
			</div>
		<br/>
		</div>
		<br/>
	</xsl:for-each>

	<p>Generated by <a href="http://opensource.adobe.com/wiki/display/flexpmd/FlexPMD">FlexPMD</a> on <xsl:value-of select="//pmd/@timestamp"/>.</p>

</xsl:template>

</xsl:stylesheet>
